#!/bin/bash

database="`pwd`/i80node.db"
logfile="`pwd`/allocnd.log"
alloccmd="`pwd`/sshalloc"
freecmd="`pwd`/sshfree"

if [[ ! -f "$database" ]]; then
	touch "$database"
	chmod 0644 "$database"
fi

if [[ ! -f "$logfile" ]]; then
	touch "$logfile"
	chmod 0644 "$logfile"
fi

if [[ ! -d "$1" ]]; then
	echo "argument must be a directory"
	exit 1
fi

inotifywait -m -e create --format "%w %f" "$1" |
while read path file; do
	if [[ ! -f "$path$file" ]]; then
		continue
	fi
	user=$file
	if [ -n "`head -n1 "$path$file" | sed -e '/^REQUEST [0-9]*-[0-9]*$/!d'`" ]; then
		from=`head -n1 "$path$file" | sed -e 's/^REQUEST \([0-9]*\)-.*$/\1/'`
		to=`head -n1 "$path$file" | sed -e 's/^.*-\([0-9]*\)$/\1/'`
		conflict=false
		while read _from _to _user _jid1 _jid2; do
			if [[ ($from -ge $_from && $from -le $_to) || ($_from -ge $from && $_from -le $to) ]]; then
				conflict=true
				echo "request conflicting with reservation from `date -d @$from` to `date -d @$to` by $_user" >> $logfile
				break
			elif [[ ($to -ge $_from && $to -le $_to) || ($_to -ge $from && $_to -le $to) ]]; then
				conflict=true
				echo "request conflicting with reservation from `date -d @$from` to `date -d @$to` by $_user" >> $logfile
				break
			fi
		done < "$database"
		if [[ "$conflict" = true ]]; then
			continue
		fi
		s_from=`date -d @$from "+%R %D"`
		s_to=`date -d @$to "+%R %D"`
		echo "registering reservation of `hostname` for $user from $s_from to $s_to" >> $logfile
		jid1=`echo "$alloccmd $user" | at $s_from 2>&1 | grep "job" | sed -e 's/^job \([0-9]*\) at .*$/\1/'`
		jid2=`echo "$freecmd $user" | at $s_to 2>&1 | grep "job" | sed -e 's/^job \([0-9]*\) at .*$/\1/'`
		echo "$from $to $user $jid1 $jid2" >> "$database"
	elif [[ -n "`head -n1 "$path$file" | sed -e '/^DELETE [1-9][0-9]*$/!d'`" ]]; then
		id=`head -n1 "$path$file" | sed -e 's/^DELETE \([1-9][0-9]*\)$/\1/'`
		entry=`tail -n+$id "$database" | head -n1`
		if [[ -z "$entry" ]]; then
			echo "could not find reservation with id '$id'" >> $logfile
			continue
		fi
		_user=`echo $entry | sed -e 's/^.* .* \(.*\) .* .*$/\1/'`
		if [[ $user != $_user ]]; then
			echo "you cannot delete a reservation made by user '$_user'" >> $logfile
			continue
		fi
		from=`echo $entry | sed -e 's/^\(.*\) .* .* .* .*$/\1/'`
		to=`echo $entry | sed -e 's/^.* \(.*\) .* .* .*$/\1/'`
		jid1=`echo $entry | sed -e 's/^.* .* .* \(.*\) .*$/\1/'`
		jid2=`echo $entry | sed -e 's/^.* .* .* .* \(.*\)$/\1/'`
		echo "deleting reservation from `date -d @$from` to `date -d @$to`" >> $logfile
		atrm $jid1 $jid2
		sed -i "/$entry/d" "$database"
	else
		echo "unrecognized command" >> $logfile
	fi
done

