#!/bin/sh

echo "`date`: restart ssh with AllowUsers=$1" >> sshd.commands

# if [[ -z `grep "AllowUsers root" /etc/ssh/sshd_config` ]]; then
# 	echo "AllowUsers root >> /etc/ssh/sshd_config
# fi
# echo "AllowUsers $1" >> /etc/ssh/sshd_config
# /etc/init.d/ssh restart

